☁️ chore(automation): Applying changes from upstream repository.

diff --git a/.config/taskfiles/docker/Taskfile.yml b/.config/taskfiles/docker/Taskfile.yml
--- a/.config/taskfiles/docker/Taskfile.yml
+++ b/.config/taskfiles/docker/Taskfile.yml
@@ -49,6 +49,7 @@ tasks:
       start: Running Docker build sequence
       success: Finished running Docker build sequence
     cmds:
+      - task: ensure:running
       - task: taskfile:deps
       - |
         if [ -d ./test/structure ]; then
@@ -85,9 +86,25 @@ tasks:
             task docker:build:fat
           fi
         fi
-    preconditions:
-      - sh: test -f Dockerfile
-        msg: The `Dockerfile` must be present in order to build it
+
+  ensure:running:
+    summary: |
+      Ensures Docker Desktop is running if on a macOS machine.
+    cmds:
+      - |
+        if ! docker stats --no-stream; then
+          if [ -f /Applications/Docker.app ]; then
+            open /Applications/Docker.app
+            while (! docker stats --no-stream); do
+              echo "Waiting for Docker to launch..."
+              sleep 1
+            done
+          else
+            .config/log error 'Docker is either not running or not installed!'
+          fi
+        fi
+    status:
+      - '[[ "{{OS}}" != "darwin" ]]'
 
   login:
     deps:
@@ -97,9 +114,12 @@ tasks:
       start: Logging into DockerHub registry with `{{.DOCKERHUB_USER}}`
       success: Authenticated to DockerHub registry with `{{.DOCKERHUB_USER}}`
     cmds:
-      - echo "$DOCKERHUB_REGISTRY_PASSWORD" | docker login -u {{.DOCKERHUB_USER}} --password-stdin
-    preconditions:
-      - test -n "$DOCKERHUB_REGISTRY_PASSWORD"
+      - |
+        if [ -n "$DOCKERHUB_REGISTRY_PASSWORD" ]; then
+          echo "$DOCKERHUB_REGISTRY_PASSWORD" | docker login -u {{.DOCKERHUB_USER}} --password-stdin
+        else
+          .config/log warn 'The `DOCKERHUB_REGISTRY_PASSWORD` is not an environment variable. This is required to login to DockerHub.'
+        fi
 
   prepare:
     cmds:
@@ -221,9 +241,15 @@ tasks:
     vars:
       DOCKERHUB_DESCRIPTION:
         sh: jq -r '.description' package.json
+    env:
+      DOCKER_PASS:
+        sh: echo "$DOCKERHUB_REGISTRY_PASSWORD"
+      DOCKER_USER: '{{.DOCKERHUB_USER}}'
     cmds:
-      - docker pushrm {{.DOCKER_IMAGE}}
-      - docker pushrm --short '{{.DOCKERHUB_DESCRIPTION}}' {{.DOCKER_IMAGE}}
+      - cmd: docker pushrm {{.DOCKER_IMAGE}}
+        ignore_error: true
+      - cmd: docker pushrm --short '{{.DOCKERHUB_DESCRIPTION}}' {{.DOCKER_IMAGE}}
+        ignore_error: true
 
   shell:
     deps:
diff --git a/.config/taskfiles/install/Taskfile-software.yml b/.config/taskfiles/install/Taskfile-software.yml
--- a/.config/taskfiles/install/Taskfile-software.yml
+++ b/.config/taskfiles/install/Taskfile-software.yml
@@ -54,6 +54,15 @@ tasks:
     status:
       - type axel > /dev/null
 
+  bfg:
+    run: once
+    cmds:
+      - task: install:software
+        vars:
+          PACKAGE: bfg
+    status:
+      - type bfg > /dev/null
+
   brew:
     run: once
     log:
@@ -145,6 +154,12 @@ tasks:
     cmds:
       - task: common:windows
 
+  bundle:
+    deps:
+      - brew
+    cmds:
+      - brew tap Homebrew/bundle
+
   codeclimate:
     cmds:
       - task: install:software
@@ -185,15 +200,25 @@ tasks:
       LINUX_FAMILY:
         sh: |
           if [ -f "/etc/debian_version" ]; then
-            echo "debian"
+            echo 'debian'
           elif [ -f "/etc/redhat-release" ]; then
-            echo "redhat"
+            echo 'redhat'
           elif [ -f "/etc/arch-release" ]; then
-            echo "archlinux"
+            echo 'archlinux'
           elif [ -f "/etc/alpine-release" ]; then
-            echo "alpine"
+            echo 'alpine'
+          elif type apk &> /dev/null; then
+            echo 'alpine'
+          elif type apt-get &> /dev/null; then
+            echo 'debian'
+          elif type dnf &> /dev/null || type yum &> /dev/null; then
+            echo 'redhat'
+          elif type pacman &> /dev/null; then
+            echo 'archlinux'
+          elif type yum &> /dev/null; then
+            echo 'redhat'
           else
-            echo "unknown"
+            echo 'unknown'
           fi
     log:
       error: Failed to ensure basic system dependencies are installed
@@ -482,6 +507,7 @@ tasks:
     run: once
     cmds:
       - task: docker:{{OS}}
+      - task: :docker:ensure:running
     status:
       - type docker > /dev/null
 
@@ -673,7 +699,16 @@ tasks:
         vars:
           PACKAGE: glab
     status:
-      - type
+      - type glab > /dev/null
+
+  glow:
+    run: once
+    cmds:
+      - task: install:software
+        vars:
+          PACKAGE: glow
+    status:
+      - type glow > /dev/null
 
   go:
     run: once
@@ -724,6 +759,11 @@ tasks:
         vars:
           PACKAGE: anchore/grype/grype
 
+  gum:
+    run: once
+    cmds:
+      - task: :install:go:gum
+
   gzip:
     run: once
     cmds:
@@ -735,6 +775,13 @@ tasks:
           PACKAGE: gzip
     status:
       - type gzip > /dev/null
+
+  heroku:
+    run: once
+    cmds:
+      - task: install:software
+        vars:
+          PACKAGE: heroku/brew/heroku
 
   hey:
     run: once
@@ -784,11 +831,27 @@ tasks:
       - type qemu-system-x86_64 > /dev/null
 
   node:
+    deps:
+      - common
+      - volta
+    run: once
+    cmds:
+      - task: node:install
+    status:
+      - type node &> /dev/null
+
+  node:install:
+    cmds:
+      - |
+        . "$HOME/.profile" &> /dev/null || true
+        volta install node
+
+  openssl:
     run: once
     cmds:
       - task: install:software
         vars:
-          PACKAGE: node
+          PACKAGE: openssl
 
   p7zip:
     run: once
@@ -846,9 +909,35 @@ tasks:
       - pipx ensurepath
 
   pipx:linux:
+    deps:
+      - pipx:linux:brew
+      - pipx:linux:system
+
+  pipx:linux:brew:
     cmds:
+      - brew install pipx
+      - pipx ensurepath
+    status:
+      - '! type brew > /dev/null'
+
+  pipx:linux:system:
+    deps:
+      - python
+    cmds:
+      - task: system
+        vars:
+          PACKAGE: python3-pip
+      - task: system
+        vars:
+          PACKAGE: python3-venv
+      - |
+        if ! type pip3; then
+          python3 -m ensurepip > /dev/null
+        fi
       - python3 -m pip install --user pipx
       - python3 -m pipx ensurepath
+    status:
+      - type brew > /dev/null
 
   pipx:windows:
     log:
@@ -887,6 +976,8 @@ tasks:
       - exit 1
 
   python:
+    deps:
+      - common
     run: once
     cmds:
       - task: brew
@@ -911,6 +1002,56 @@ tasks:
           PACKAGE: python@3.10
     status:
       - type python3 > /dev/null
+
+  python:pip:
+    run: once
+    cmds:
+      - |
+        PIP_LOCATION="$(which pip)"
+        PIP3_LOCATION="$(which pip3)"
+        if [ "$USER" == "root" ]; then
+          if type pip &> /dev/null && type pip3 &> /dev/null; then
+            rm "$PIP_LOCATION"
+            ln -s "$PIP3_LOCATION" "$PIP_LOCATION"
+          elif type pip3 &> /dev/null; then
+            ln -s "$PIP3_LOCATION" /usr/bin/pip
+          elif type pip &> /dev/null; then
+            ln -s "$PIP_LOCATION" /usr/bin/pip3
+          else
+            .config/log warn 'Both `pip` and `pip3` appear to be missing'
+          fi
+        elif type sudo &> /dev/null && sudo -n true; then
+          if type pip &> /dev/null && type pip3 &> /dev/null; then
+            sudo rm "$PIP_LOCATION"
+            sudo ln -s "$PIP3_LOCATION" "$PIP_LOCATION"
+          elif type pip3 &> /dev/null; then
+            sudo ln -s "$PIP3_LOCATION" /usr/bin/pip
+          elif type pip &> /dev/null; then
+            sudo ln -s "$PIP_LOCATION" /usr/bin/pip3
+          else
+            .config/log warn 'Both `pip` and `pip3` appear to be missing'
+          fi
+        elif type sudo &> /dev/null; then
+          if type pip &> /dev/null && type pip3 &> /dev/null; then
+            .config/log info 'Running `sudo rm $(which pip)`'
+            sudo rm "$PIP_LOCATION"
+            sudo ln -s "$PIP3_LOCATION" "$PIP_LOCATION"
+          elif type pip3 &> /dev/null; then
+            .config/log info 'Running `sudo ln -s $(which pip3) /usr/bin/pip`'
+            sudo ln -s "$PIP3_LOCATION" /usr/bin/pip
+          elif type pip &> /dev/null; then
+            .config/log info 'Running `sudo ln -s $(which pip) /usr/bin/pip3`'
+            sudo ln -s "$PIP_LOCATION" /usr/bin/pip3
+          else
+            .config/log warn 'Both `pip` and `pip3` appear to be missing'
+          fi
+        else
+           .config/log warn '`sudo` unavailable and user has no permissions'
+        fi
+    status:
+      - which pip > /dev/null
+      - which pip3 > /dev/null
+      - '[ "$(which pip)" == "$(which pip3)" ]'
 
   python:windows:
     log:
@@ -949,8 +1090,12 @@ tasks:
           PACKAGE: peak/tap/s5cmd
 
   sentry:
+    run: once
     cmds:
-      - task: :install:github:sentry
+      - task: install:software
+        vars:
+          BIN_NAME: sentry-cli
+          PACKAGE: getsentry/tools/sentry-cli
 
   snapcraft:
     run: once
@@ -1000,28 +1145,38 @@ tasks:
   system:
     vars:
       PACKAGE: '{{if .PACKAGE}}{{.PACKAGE}}{{else}}{{.CLI_ARGS}}{{end}}'
-    log:
-      error: Failed to install `{{.PACKAGE}}` with the system package manager
-      start: Attempting to install `{{.PACKAGE}}` using the system package manager
     cmds:
-      - task: system:apk
-        vars:
-          PACKAGE: '{{.PACKAGE}}'
-      - task: system:apt-get
-        vars:
-          PACKAGE: '{{.PACKAGE}}'
-      - task: system:dnf
-        vars:
-          PACKAGE: '{{.PACKAGE}}'
-      - task: system:pacman
-        vars:
-          PACKAGE: '{{.PACKAGE}}'
-      - task: system:yum
-        vars:
-          PACKAGE: '{{.PACKAGE}}'
-      - task: system:macos
-        vars:
-          PACKAGE: '{{.PACKAGE}}'
+      - .config/log start 'Attempting to install `{{.PACKAGE}}` using the system package manager'
+      - |
+        if [ -f "/etc/redhat-release" ]; then
+          if type dnf &> /dev/null; then
+            task install:software:system:dnf -- '{{.PACKAGE}}'
+          else
+            task install:software:system:yum -- '{{.PACKAGE}}'
+          fi
+        elif [ -f "/etc/debian_version" ]; then
+          task install:software:system:apt-get -- '{{.PACKAGE}}'
+        elif [ -f "/etc/arch-release" ]; then
+          task install:software:system:pacman -- '{{.PACKAGE}}'
+        elif [ -f "/etc/alpine-release" ]; then
+          task install:software:system:apk -- '{{.PACKAGE}}'
+        elif type dnf &> /dev/null; then
+          task install:software:system:dnf -- '{{.PACKAGE}}'
+        elif type yum &> /dev/null; then
+          task install:software:system:yum -- '{{.PACKAGE}}'
+        elif type apt-get &> /dev/null; then
+          task install:software:system:apt-get -- '{{.PACKAGE}}'
+        elif type pacman &> /dev/null; then
+          task install:software:system:pacman -- '{{.PACKAGE}}'
+        elif type apk &> /dev/null; then
+          task install:software:system:apk -- '{{.PACKAGE}}'
+        else
+          if [ '{{OS}}' == 'darwin' ]; then
+            task install:software:system:macos -- '{{.PACKAGE}}'
+          else
+            .config/log error 'No matching system. Cannot continue with installation.' && exit 1
+          fi
+        fi
     status:
       - type {{.PACKAGE}} > /dev/null || [ '{{.PACKAGE}}' == 'null' ]
 
@@ -1127,6 +1282,14 @@ tasks:
     status:
       - '[ -z "$(which yum)" ]'
 
+  task:
+    run: once
+    cmds:
+      - |
+        if [[ "$(which task)" == *'.local/bin/task' ]] && command -v brew > /dev/null && ! brew list go-task/tap/go-task; then
+          brew install go-task/tap/go-task
+        fi
+
   tokei:
     run: once
     cmds:
@@ -1195,7 +1358,7 @@ tasks:
       - task: vmware:{{OS}}
       - task: exit:notice:restart
     status:
-      - type vmware > /dev/null
+      - type vmrun > /dev/null
 
   vmware:darwin:
     run: once
@@ -1210,6 +1373,18 @@ tasks:
       - task: :install:install-doctor
         vars:
           SOFTWARE: vmware
+
+  volta:
+    run: once
+    cmds:
+      - .config/log info 'Installing Volta'
+      - curl https://get.volta.sh | bash
+      - |
+        . "$HOME/.profile" &> /dev/null || true
+        volta setup
+      - .config/log success 'Successfully setup Volta'
+    status:
+      - type volta > /dev/null
 
   yarn:
     tags:
